### ISSUE TITLE
Kubewarden policy to validate cosign images

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#1183]
In order to validate images used for upgrades in kubernetes, we can have a kubewarden policy to validate cosign images and prevent upgrades from being pulled and hitting nodes.

**Comment by mudler** [comment]
I've pinged the kubewarden team as I could not find any policy for cosign in https://hub.kubewarden.io/, if that's the case we should implement our own policy

**Comment by mudler** [comment]
I've checked in with @flavio and at the moment this doesn't seems to be technically possible with Kubewarden but it's in the roadmap. 

Let's postpone this as there is no pressure for it right now, in the case we need a temporary solution we can write a custom admission controller for the purpose and replace it later with a kubewarden policy.

**Comment by mudler** [comment]
This seems to be possible now

**Comment by flavio** [comment]
This is the kubewarden policy that implements image verification: https://github.com/kubewarden/verify-image-signatures

Feel free to reach out if something is missing or if you want to propose improvements

**Comment by mudler** [comment]
From a preliminar test the policy seems sufficent as it is gating upgrades. I'm checking out now if I can make an upgrade going through it and documenting all the steps.

**Comment by mudler** [comment]
Seems to be fixed upstream now, having a look at it again

**Comment by viccuad** [comment]
The DNS resolution failure seems weird to be fair. I wonder if it is a fluke.

We just released v0.1.5 of the policy. It has a new `github_actions` signature setting, that is more secure (prevents about attackers consuming GHA reusable workflows and passing signatures as them) and also simpler to use (upcoming blog post in kubewarden.io/blog)

```
apiVersion: policies.kubewarden.io/v1alpha2
kind: ClusterAdmissionPolicy
metadata:
  name: verify-image-signatures-policy
spec:
  module: registry://ghcr.io/kubewarden/policies/verify-image-signatures:v0.1.5
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
    operations:
    - CREATE
    - UPDATE
  mutating: true
  settings:
    signatures:
        - image: "*"
          github_actions: 
              owner: "c3os-io"
              repo: "c3os" # optional
```

The second error, the mutation one, may have been because the ClusterAdmissionPolicy was missing `.spec.mutating: true`. 
By default, the policy will validate the container tag and by default mutate the container definition to append the digest of the verified tag (digests are immutable, tags are mutable).

If one doesn't want the policy to mutate, they can set `.spec.settings.modifyImagesWithDigest: false` (default is true), and then it is irrelevant if the policy has `.spec.mutating: true`.
