### ISSUE TITLE
ci: Add a test for the sample repo

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#144]
At the moment, we are not testing if our changes are breaking the workflow in https://github.com/rancher-sandbox/cos-toolkit-sample-repo which is our quickstart for newcomers.

**Describe the solution you would like**
A step in the CI workflow which builds the sample repo as advertized in the README against the changes in the patchset

Sub-Issues/PR:
- https://github.com/rancher-sandbox/cOS-toolkit/pull/205
- #274

**Comment by Itxaka** [comment]
I had a quick look at this, and it seems that we can get this to be automated by using workflow_dispatch and a personal access token.

Basically making a build workflow on the sample repo that runs `on: workflow_dispatch` and then at the end of a cos-toolkit master test run we fire that event using `https://github.com/marketplace/actions/workflow-dispatch` like this:

```
      - name: Invoke CI in cos-toolkit-sample-repo
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: NAME OF THE REMOTE WORKFLOW
          repo: rancher-sandbox/cos-toolkit-sample-repo 
          token: ${{ secrets.PERSONAL_TOKEN }}
```

It should trigger the mentioned workflow there. This way we could have not just one for the sample repo, but for other test appliances that we have.

Of course...we would need to check the CI of those sample repos manually to check if we broke them...but we could always automate that in the sample repos to post to slack or whatever I guess
