### ISSUE TITLE
Shared version/categories between packages in a collection

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#612]
**Is your feature request related to a problem? Please describe.**
There might be collections with packages between all in the same categories and the same version

**Describe the solution you'd like**
A common `version` and `category` in the `collection.yaml` file, e.g.

```yaml
packages:
- name: "bbb"
- name: "aaa"
- name: "ccc"
  version: "1.0"
  category: "bar"
# ...
version: "0.1"
category: "system"
```

**Describe alternatives you've considered**
YAML Anchors

**Additional context**
See the cOS package definition
