### ISSUE TITLE
Enhance cloud-init syntax support

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#618]
**Is your feature request related to a problem? Please describe.**
Currently we partially support cloud-init syntax, but it is limited to a small subset of the features.

**Describe the solution you'd like**
To extend the syntax already supported to include:
- `growpart` (which can be provided by the Layout plugin) 
-  `uid` and  `lock_passwd` into the users fields

**Additional context**
So lima can load cOS images cc @ibuildthecloud 

```yaml
#cloud-config
# vim:syntax=yaml

growpart:
  mode: auto
  devices: ['/']

users:
  - name: "darren"
    uid: "1000"
    homedir: "/home/darren.linux"
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh-authorized-keys:
    - ...

write_files:
 - content: |
      #!/bin/sh
      set -eux
      LIMA_CIDATA_MNT="/mnt/lima-cidata"
      LIMA_CIDATA_DEV="/dev/disk/by-label/cidata"
      mkdir -p -m 700 "${LIMA_CIDATA_MNT}"
      mount -o ro,mode=0700,dmode=0700,overriderockperm,exec,uid=0 "${LIMA_CIDATA_DEV}" "${LIMA_CIDATA_MNT}"
      export LIMA_CIDATA_MNT
      exec "${LIMA_CIDATA_MNT}"/boot.sh
   owner: root:root
   path: /var/lib/cloud/scripts/per-boot/00-lima.boot.sh
   permissions: '0755'
```

**Comment by Itxaka** [comment]
there was a request for `locked_passwd` as well on the user fields

**Comment by mudler** [comment]
> there was a request for `locked_passwd` as well on the user fields

completely missed it! updated the card, thanks!

**Comment by mudler** [comment]
```yaml
growpart:
  mode: auto
  devices: ['/']
```
is a bit unclear to me. In our case `/` is mounted over an image, so growing partition might have a different meaning, my expectations here is to have `COS_PERSISTENT` to be enlarged instead of the image file
