### ISSUE TITLE
repository does not contain arch on default luet repo

### ISSUE THREAD

**Issue by Itxaka** [rancher-sandbox/cOS-toolkit#742]
For all of our generated arm64 artifacts, the repository set by default on the luet package is pointing to the default x86_64, thus breaking any upgrade

```
cos:~ # uname -a
Linux cos 5.3.18-59.24-default #1 SMP Mon Sep 13 15:06:42 UTC 2021 (2f872ea) aarch64 aarch64 aarch64 GNU/Linux
cos:~ # cat /etc/luet/luet.yaml 
# For a full reference, see:
# https://luet-lab.github.io/docs/docs/getting-started/#configuration
logging:
  color: false
  enable_emoji: false
general:
   debug: false
   spinner_charset: 9
repositories:
- name: "cos"
  description: "cOS official"
  type: "docker"
  enable: true
  cached: true
  priority: 1
  verify: false
  urls:
  - "quay.io/costoolkit/releases-green"
 ```

**Comment by mudler** [comment]
valid point, this should be interpolated here: https://github.com/rancher-sandbox/cOS-toolkit/blob/master/packages/cloud-config/oem/02_upgrades.yaml#L37, which actually gets templated after the codename defined here: https://github.com/rancher-sandbox/cOS-toolkit/blob/master/values/green-arm64.yaml#L3

**Comment by Itxaka** [comment]
ỳup, seems like a simple change :D

**Comment by Itxaka** [comment]
@mudler would be awesome if there was a way of template interpolation for random files during building, say it would pick values from .Values if you marked the file as a template or something like that.

Like for example:

```
requires:
- name: "cos-setup"
  category: "system"
  version: ">=0"
parse_templates:
  - /system/oem/02_upgrades.yaml
steps:
- mkdir -p /system /oem
- cp -rfv oem /system
- chmod -R 600 /system/oem
```

And that would automatically parse and replace whatever values in there during build time before packing.

Oh well, one can dream eh? ;)
