### ISSUE TITLE
Too many CI failures

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#917]
**cos-toolkit version:**
Since at least https://github.com/rancher-sandbox/cOS-toolkit/commit/a684abb22e8b91dda22428c14fee4f6b466d203c

**CPU architecture, OS, and Version:**

**Describe the bug**
CI jobs are sporadically failing more frequently, preventing time to time to go for the full flow. we should look after into optimizing the jobs, or relax our test suites (maybe splitting?)

**To Reproduce**
There was no full green CI run since the commit above

**Expected behavior**

**Logs**

**Additional context**

**Comment by davidcassany** [comment]
In addition to some installer tests failures we also started having having failures due to not having enough disk space during the build.

**Comment by Itxaka** [comment]
Installer tests can be splitted in different paths with the use of regex, but that would take precious macosX instances (we have a total of 5 in parallel)

For now, the installer tests are NOT required for a job to pass and be merged, so there is that :/

**Comment by mudler** [comment]
not really related, but this workaround will make things worse: https://github.com/rancher-sandbox/cOS-toolkit/pull/920. Maybe we shall fallback to job cancelling via action? e.g.

```
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      #- name: Run Tests
      #  uses: actions/setup-node@v1
      #  run: node test.js
      # ... etc
```
