### ISSUE TITLE
Autobump for firmware/* packages

### ISSUE THREAD

**Issue by mudler** [rancher-sandbox/cOS-toolkit#932]
**Is your feature request related to a problem? Please describe.**
Firmware packages are continuously being rebuilt, thus builds from scratch (without any docker cache) would likely hit 404 continously

**Describe the solution you'd like**
We should keep packages specs up-to-date

**Describe alternatives you've considered**

**Additional context**
We can use the same mechanism as we bump other packages, e.g. `golang` and annotate in the definition spec labels to let @cOS-cibot handle that. For example `u-boot-rpiarm64` using #919 to scrape XML from openSUSE repositories  :

```yaml
      autobump.hook: |
        curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/$(curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/repodata/repomd.xml | dasel select -p xml 'repomd.data.[0].location.-href') | gunzip | dasel -r xml -p json | jq '.metadata.package[] | select(.name=="u-boot-rpiarm64") | select(.arch!="src").version | map(.)[2] + map(.)[1]' -r
      autobump.version_hook: |
        curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/$(curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/repodata/repomd.xml | dasel select -p xml 'repomd.data.[0].location.-href') | gunzip | dasel -r xml -p json | jq '.metadata.package[] | select(.name=="u-boot-rpiarm64") | select(.arch!="src").version | map(.)[2] + map(.)[1]' -r

      # We do assume that checksum is sha256
      autobump.checksum: |
        curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/$(curl -s -L https://download.opensuse.org/repositories/hardware:/boot/openSUSE_Factory_ARM/repodata/repomd.xml | dasel select -p xml 'repomd.data.[0].location.-href') | gunzip | dasel -r xml -p json | jq '.metadata.package[] | select(.name=="u-boot-rpiarm64") | select(.arch!="src").checksum."#text"' -r
```
